# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(max_length=4),
        ),
    ]
